CREATE GLOBAL TEMPORARY TABLE V6_TEMP_TABLE ON COMMIT PRESERVE ROWS  AS SELECT * FROM V6_ORIG_TABLE_TEMP WHERE 1<>1;
SELECT * FROM V6_TEMP_TABLE
INSERT INTO V6_TEMP_TABLE SELECT * FROM V6_ORIG_TABLE_TEMP WHERE entity_id='GICPORT1' AND  effective_date='1-JAN-2017' AND SECURITY_ALIAS=680916795;
UPDATE V6_TEMP_TABLE SET ENTITY_ID='V6M_ENT',trans_num='V6M_ENT_999999',orig_trans_num='V6M_ENT_999999',CASH_INT='666999999'
DELETE FROM V6_TEMP_TABLE;
INSERT INTO V6_ORIG_TABLE_TEMP select * from V6_TEMP_TABLE
